### ISSUE TITLE
Support for PlaceholderWithDefault

### ISSUE THREAD

**Issue by jlebensold** [tf-coreml/tf-coreml#82]
Hi there,

this is a really exciting project! I'm getting this error when trying to convert MobileNet from the code poets example:

`NotImplementedError: Unsupported Ops of type: PlaceholderWithDefault`

I noticed that `Placeholder` is implemented. Do you think `PlaceholderWithDefault` will be in scope?

Many thanks!

**Comment by lahayeg** [comment]
Hi,
same issue. Installed from pip not from source. Seems strange because test case show convertion of MobileNet...

**Comment by aseemw** [comment]
Hi, Thank you for pointing out this issue. The support for the "PlaceholderWithDefault" op will be added soon.

The mobilenet models linked to in the readme of this repo, the ones hosted on Google's website, do not have this op and can be converted by the current converter. The mobilenet model generated in the code poets repo does have the "PlaceholderWithDefault" op whose support will be added soon.

**Comment by aseemw** [comment]
Please check PR#83. Should resolve the issue.

**Comment by jlebensold** [comment]
This is great thanks aseemw!

**Comment by aseemw** [comment]
Fixed in PR#83

**Comment by nivim** [comment]
Hi @aseemw,
I'm still getting error - Unsupported Ops of type: PlaceholderWithDefault
Any thoughts / suggestions?
I'm trying to convert the tensor-flow for poets example with the inception_v3 example.


full error:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-33-e2c48f2dbcd9> in <module>()
     20         green_bias = -1,
     21         blue_bias = -1,
---> 22         image_scale = 2.0/255.0)
     23 
     24 # MLModel saved at location: ./inception_v3.mlmodel

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.pyc in convert(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.pyc in _convert_pb_to_mlmodel(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.pyc in _check_unsupported_ops(ops, output_feature_names)

NotImplementedError: Unsupported Ops of type: PlaceholderWithDefault

**Comment by aseemw** [comment]
Hi @nivim, can you please pull the latest version of this repo and install it from [source](https://github.com/tf-coreml/tf-coreml#install-from-source) (using pip install -e . ). The error should go away then.

**Comment by nivim** [comment]
Thanks @aseemw !
Already did that once according to your comments in another issue,but I had to actively uninstall the former package and then install the latest one for it to take effect.

Works perfect now, Thank you!

**Comment by mdramos** [comment]
any support for `Pow` coming soon?

**Comment by mdramos** [comment]
I have a successful go at `pow`, using `add_unary` ... just wondering what would determine a correct **alpha** ... right now I'm just using a assumed value

**Comment by mdramos** [comment]
^ disregard, found:
```
 const_name = compat.as_bytes(op.inputs[1].name)
 const_val = context.consts[const_name]
```
